### ISSUE TITLE
No landscape artwork

### ISSUE THREAD

**Issue by ciwy85** [henryjfry/fryhenryj#1]
In v0.0.3 widget made from the addon instead of using landscape artwork is stretching poster.
![15589705513635465438009103346032](https://user-images.githubusercontent.com/36696737/58428865-d3033600-809b-11e9-8fc0-458744fe9c03.jpg)

If I remember correctly it wasn't doing it in first release.
Ps. I have added some new shows to my library and they don't show up in the addon is this intentional?

**Comment by henryjfry** [comment]
New shows wouldnt show up until you start watching them.  Ie have watched at least one episode.
This is the same behaviour as in progress and means only your active shows will appear by default.

I dont use any landscape views so this wasnt something I had noticed.  You could modify the line where "setArt" to choose something which is going to work for you.  The options are
"season.poster", "thumb",  "tvshow.banner",  "tvshow.fanart", "tvshow.poster" for TV show, I cant find the episode options right now, id have to figure out which one is for landscape.  Ill look into it but probably not for a day or two.

**Comment by henryjfry** [comment]
Here are the log outputs for:

#    xbmc.log(str(episode_details['episodedetails']['art']),level=2)
{u'fanart': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2ffanart%2foriginal%2f276564-16.jpg/', u'poster': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fposters%2f276564-25.jpg/', u'banner': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fgraphical%2f276564-g11.jpg/'}

#    xbmc.log(str(tvshow_details['art']),level=2)

{u'tvshow.fanart': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2ffanart%2foriginal%2f314544-8.jpg/', u'tvshow.poster': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fposters%2f5bec7fcb2f698.jpg/', u'season.poster': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fseasons%2f5bec8ea769eb0.jpg/', u'tvshow.banner': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fgraphical%2f5c1837398ad64.jpg/', u'thumb': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fepisodes%2f314544%2f5682081.jpg/'}
2019-05-28 21:45:06.122 T:3182408416  NOTICE: {u'fanart': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2ffanart%2foriginal%2f314544-8.jpg/', u'poster': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fposters%2f5bec7fcb2f698.jpg/', u'banner': u'image://http%3a%2f%2fwww.thetvdb.com%2fbanners%2fgraphical%2f5c1837398ad64.jpg/'}

And set art has the options:

  - Some default art values (any string possible):
        - thumb : string - image filename
        - poster : string - image filename
        - banner : string - image filename
        - fanart : string - image filename
        - clearart : string - image filename
        - clearlogo : string - image filename
        - landscape : string - image filename
        - icon : string - image filename

So you could add a landscape option for fanart or banner?
I wouldnt know what other art would work better in landscape.

**Comment by ciwy85** [comment]
I see,  thanks. The option I use is poster but it turns in to landscape when highlighted. There is no rush I will just switch to poster for now.

**Comment by henryjfry** [comment]
Closed v0.0.4
