### ISSUE TITLE
[Feature Request] Export episode list as playlist

### ISSUE THREAD

**Issue by tam1m** [henryjfry/fryhenryj#2]
It would be nice to have the addon export to a xps playlist, as Kodi on Android TV uses it's playlists to populate [Channels](https://developer.android.com/training/tv/discovery/recommendations-channel) for the Android TV Homescreen

**Comment by henryjfry** [comment]
Im planning on adding that or forking the add-on at some stage but smart playlists cant apply multiple limits/filters so I'm not sure it can be done with a single smart playlists.

I did build a script that does this checkout my Reddit fryhenryj

**Comment by henryjfry** [comment]
https://www.reddit.com/r/Addons4Kodi/comments/brsf3r/next_up_playlist_automatically_generated/

**Comment by henryjfry** [comment]
Hey so I made a new version of the add-on which does that, next_playlist. 

It's in my repo, a link for Kodi:

https://henryjfry.github.io/repository.nextup/repo/
